### ISSUE TITLE
第九章翻译错误

### ISSUE THREAD

**Issue by midare16** [wizardforcel/think-dast-zh#3]
63页
After `put `calls `findEntry`, everything else is constant time. Remember that entries is an `ArrayList`, so adding an element at the end is constant time, on average.

`put `调用 `findEntry `之后，其他一切都是常数时间。记住这个 entries 是一个 `ArrayList `，
 **所以降魔为添加元素平均是常数时间。**

**Comment by wizardforcel** [comment]
fixed
